[common]
server_addr = bj.zyfrp.vip
server_port = 899
tcp_mux = true
protocol = tcp
user = 1762825322469
token = 566#ff
dns_server = 114.114.114.114

##
[1768300942]
type = tcp
local_ip = 127.0.0.1
local_port = 22
remote_port = 7777
use_encryption = true
use_compression = true
